build-di:
	flutter packages pub run build_runner build --delete-conflicting-outputs && find . -name "*.inject.summary" |xargs rm -- && find . -name "*.inject.dart" -size 0 |xargs rm --

run-web:
	flutter run -d chrome --web-port=1305